#!/usr/bin/env python3
"""
Stage 2 builder: raw registry JSON -> lembaga-official.csv.

Hand-authored enrichment (descriptions, majors, UKM fields, dedupe,
name normalization) over data/raw/lembaga-2026-08-02.json.
Descriptions: neutral, factual, 1-2 Indonesian sentences, derived from
visi/misi + name; never invented. Unknown facts stay blank (email = Stage 3,
founding_date = nullable since migration 0017).

Run: python3 scripts/build-lembaga-csv.py
Prints: row counts + QA flags requiring human review.
"""

import csv
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RAW = os.path.join(ROOT, "src/server/db/seeding/data/raw/lembaga-2026-08-02.json")
OUT = os.path.join(ROOT, "src/server/db/seeding/data/lembaga-official.csv")

# Himpunan: no -> (name, description, major, flag)
HIMPUNAN = {
    1: ("Himpunan Mahasiswa Informatika ITB",
        "Himpunan Mahasiswa Informatika ITB (HMIF ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Informatika serta Sistem dan Teknologi Informasi ITB, yang mewadahi pengembangan keprofesian dan kegiatan kemahasiswaan anggotanya.",
        "Teknik Informatika", ""),
    2: ("Himpunan Mahasiswa Teknik Perminyakan ITB",
        'Himpunan Mahasiswa Teknik Perminyakan "PATRA" ITB (HMTM PATRA ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Perminyakan ITB.',
        "Teknik Perminyakan", "needs_review: visi/misi kosong di sumber; deskripsi hanya dari nama"),
    4: ("Himpunan Mahasiswa Elektroteknik ITB",
        "Himpunan Mahasiswa Elektroteknik ITB (HME ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Elektro ITB, yang menjadi ruang pengembangan diri, keprofesian, dan karya anggotanya.",
        "Teknik Elektro", ""),
    5: ("Himpunan Mahasiswa Fisika Teknik ITB",
        "Himpunan Mahasiswa Fisika Teknik ITB (HMFT-ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Fisika ITB, dengan fokus pengembangan potensi anggota sesuai watak keilmuan dan keprofesian serta kepeloporan inovasi teknologi.",
        "Teknik Fisika", ""),
    6: ("Ikatan Mahasiswa Geodesi ITB",
        "Ikatan Mahasiswa Geodesi ITB (IMG-ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Geodesi dan Geomatika ITB.",
        "Teknik Geodesi dan Geomatika", ""),
    7: ("Himpunan Mahasiswa Matematika ITB",
        "Himpunan Mahasiswa Matematika ITB (HIMATIKA ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Matematika ITB.",
        "Matematika", ""),
    8: ("Ikatan Mahasiswa Arsitektur Gunadharma ITB",
        "Ikatan Mahasiswa Arsitektur Gunadharma ITB (IMA-G ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Arsitektur ITB, yang berfokus pada penanaman semangat dan kemampuan berkarya anggotanya.",
        "Arsitektur", ""),
    9: ("Himpunan Mahasiswa Kimia 'Amisca' ITB",
        "Himpunan Mahasiswa Kimia 'Amisca' ITB (HMK 'Amisca' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Kimia ITB.",
        "Kimia", ""),
    10: ("Keluarga Mahasiswa Teknik Industri ITB",
        "Keluarga Mahasiswa Teknik Industri ITB (MTI ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Industri ITB, yang menunjang pengembangan akademik, keilmuan, dan karya anggotanya.",
        "Teknik Industri", ""),
    11: ("Himpunan Mahasiswa Oseanografi ITB",
        'Himpunan Mahasiswa Oseanografi "TRITON" ITB (HMO TRITON ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Oseanografi ITB.',
        "Oseanografi", ""),
    12: ("Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota Pangripta Loka ITB",
        "Himpunan Mahasiswa Teknik Perencanaan Wilayah dan Kota Pangripta Loka ITB (HMP PL ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Perencanaan Wilayah dan Kota ITB.",
        "Perencanaan Wilayah dan Kota", ""),
    13: ("Keluarga Mahasiswa Teknik Penerbangan ITB",
        "Keluarga Mahasiswa Teknik Penerbangan ITB (KMPN ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Penerbangan ITB.",
        "Teknik Penerbangan", ""),
    14: ("Himpunan Mahasiswa Teknik Lingkungan ITB",
        "Himpunan Mahasiswa Teknik Lingkungan ITB (HMTL ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Lingkungan ITB.",
        "Teknik Lingkungan", ""),
    15: ("Himpunan Mahasiswa Astronomi ITB",
        "Himpunan Mahasiswa Astronomi ITB (Himastron ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Astronomi ITB, yang menjadi rumah aktualisasi diri dan karya keastronomian anggotanya.",
        "Astronomi", ""),
    16: ("Himpunan Mahasiswa Mikrobiologi 'Archaea' ITB",
        "Himpunan Mahasiswa Mikrobiologi 'Archaea' ITB (HIMAMIKRO 'Archaea' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Mikrobiologi ITB.",
        "Mikrobiologi", ""),
    17: ("Ikatan Mahasiswa Metalurgi ITB",
        "Ikatan Mahasiswa Metalurgi ITB (IMMG ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Metalurgi ITB.",
        "Teknik Metalurgi", ""),
    18: ("Himpunan Mahasiswa Sumber Daya Air ITB",
        "Himpunan Mahasiswa Sumber Daya Air ITB (Himasda-ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Sumber Daya Air ITB.",
        "Teknik Sumber Daya Air", ""),
    19: ("Himpunan Mahasiswa Mesin ITB",
        "Himpunan Mahasiswa Mesin ITB (HMM ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Mesin ITB, yang menyelenggarakan kegiatan pendidikan kemahasiswaan, keprofesian, dan pengabdian masyarakat.",
        "Teknik Mesin", ""),
    20: ("Ikatan Pemuda Pemudi Desain Grafis ITB",
        "Ikatan Pemuda Pemudi Desain Grafis ITB (IPPDIG ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Desain Komunikasi Visual ITB.",
        "Desain Komunikasi Visual", ""),
    21: ("Keluarga Mahasiswa Infrastruktur Lingkungan ITB",
        "Keluarga Mahasiswa Infrastruktur Lingkungan ITB (KMIL ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Rekayasa Infrastruktur Lingkungan ITB.",
        "Rekayasa Infrastruktur Lingkungan", ""),
    22: ("Himpunan Mahasiswa Meteorologi ITB",
        'Himpunan Mahasiswa Meteorologi "Atmosphaira" ITB (HMME ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Meteorologi ITB.',
        "Meteorologi", ""),
    23: ("Himpunan Mahasiswa Biologi ITB",
        'Himpunan Mahasiswa Biologi "Nymphaea" ITB (HIMABIO ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Biologi ITB.',
        "Biologi", ""),
    24: ("Himpunan Mahasiswa Fisika ITB",
        "Himpunan Mahasiswa Fisika ITB (HIMAFI ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Fisika ITB.",
        "Fisika", ""),
    25: ("Industrial Design Student Society ITB",
        "Industrial Design Student Society ITB (INDDES ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Desain Produk ITB.",
        "Desain Produk", ""),
    26: ("Himpunan Mahasiswa Rekayasa Pertanian 'Agrapana' ITB",
        "Himpunan Mahasiswa Rekayasa Pertanian 'Agrapana' ITB (HIMAREKTA 'Agrapana' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Rekayasa Pertanian ITB.",
        "Rekayasa Pertanian", ""),
    27: ("Himpunan Mahasiswa Tambang ITB",
        "Himpunan Mahasiswa Tambang ITB (HMT-ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Pertambangan ITB.",
        "Teknik Pertambangan", ""),
    28: ("Himpunan Mahasiswa Rekayasa Hayati ITB",
        "Himpunan Mahasiswa Rekayasa Hayati ITB (HMRH ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Rekayasa Hayati ITB.",
        "Rekayasa Hayati", ""),
    29: ("Himpunan Mahasiswa Teknik Geofisika ITB",
        'Himpunan Mahasiswa Teknik Geofisika "TERRA" ITB (HIMA TG ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Geofisika ITB.',
        "Teknik Geofisika", ""),
    30: ("Himpunan Mahasiswa Teknik Material ITB",
        "Himpunan Mahasiswa Teknik Material ITB (MTM ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Material ITB.",
        "Teknik Material", "needs_review: visi/misi kosong di sumber; deskripsi hanya dari nama"),
    31: ("Himpunan Mahasiswa Teknik Geologi ITB",
        "Himpunan Mahasiswa Teknik Geologi ITB (HMTG ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Geologi ITB.",
        "Teknik Geologi", ""),
    32: ("Ikatan Mahasiswa Desain Interior ITB",
        "Ikatan Mahasiswa Desain Interior ITB (IMDI ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Desain Interior ITB, yang berfokus pada pengembangan potensi anggota dan kolaborasi berbasis keilmuan desain interior.",
        "Desain Interior", ""),
    33: ("Himpunan Mahasiswa Sipil ITB",
        "Himpunan Mahasiswa Sipil ITB (HMS ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Sipil ITB.",
        "Teknik Sipil", ""),
    34: ("Himpunan Mahasiswa Teknik Kimia ITB",
        "Himpunan Mahasiswa Teknik Kimia ITB (HIMATEK ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Kimia ITB.",
        "Teknik Kimia", ""),
    35: ("TERIKAT ITB",
        "TERIKAT (Tembikar dan Ikat) ITB adalah organisasi kemahasiswaan bagi mahasiswa program studi Kriya ITB.",
        "Kriya", "verify: major 'Kriya' disimpulkan dari singkatan (tembikar/ikat)"),
    36: ("Himpunan Mahasiswa Rekayasa Kehutanan 'Selva' ITB",
        "Himpunan Mahasiswa Rekayasa Kehutanan 'Selva' ITB (HMH 'Selva' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Rekayasa Kehutanan ITB.",
        "Rekayasa Kehutanan", ""),
    37: ("Keluarga Mahasiswa Teknik Kelautan ITB",
        "Keluarga Mahasiswa Teknik Kelautan ITB (KMKL-ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Kelautan ITB.",
        "Teknik Kelautan", ""),
    38: ("Himpunan Mahasiswa Farmasi 'Ars Praeparandi' ITB",
        "Himpunan Mahasiswa Farmasi 'Ars Praeparandi' ITB (HMF 'Ars Praeparandi' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Farmasi ITB.",
        "Farmasi", ""),
    39: ("Himpunan Mahasiswa Teknologi Pascapanen 'VADRA' ITB",
        "Himpunan Mahasiswa Teknologi Pascapanen 'VADRA' ITB (HMPP 'VADRA' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknologi Pascapanen ITB.",
        "Teknologi Pascapanen", ""),
    40: ("Visual Art Student Aggregate ITB",
        "Visual Art Student Aggregate ITB (VASA ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Seni Rupa ITB.",
        "Seni Rupa", ""),
    41: ("Himpunan Mahasiswa Teknik Pangan ITB",
        "Himpunan Mahasiswa Teknik Pangan ITB (HMPG ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknologi Pangan ITB.",
        "Teknologi Pangan", ""),
    42: ("Ikatan Mahasiswa Telekomunikasi 'Signum' ITB",
        "Ikatan Mahasiswa Telekomunikasi 'Signum' ITB (IMT 'Signum' ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Telekomunikasi ITB.",
        "Teknik Telekomunikasi", ""),
    43: ("Himpunan Mahasiswa Teknik Bioenergi dan Kemurgi ITB",
        'Himpunan Mahasiswa Teknik Bioenergi dan Kemurgi "RINUVA" ITB (HMTB "RINUVA" ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Teknik Bioenergi dan Kemurgi ITB.',
        "Teknik Bioenergi dan Kemurgi", ""),
    44: ("Keluarga Mahasiswa Manajemen ITB",
        "Keluarga Mahasiswa Manajemen ITB (KMM ITB) adalah organisasi kemahasiswaan bagi mahasiswa program studi Manajemen ITB.",
        "Manajemen", "needs_review: visi/misi kosong di sumber; deskripsi hanya dari nama"),
}

# UKM: no -> (name, description, field, flag)
UKM = {
    1: ("Unit Renang dan Polo Air ITB",
        "Unit Renang dan Polo Air ITB (URPA ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi mahasiswa ITB di cabang renang dan polo air.",
        "Olahraga", ""),
    2: ("Unit Bulu Tangkis ITB",
        "Unit Bulu Tangkis ITB (UBT ITB) adalah unit kegiatan mahasiswa yang mewadahi pengembangan minat, bakat, dan prestasi bulu tangkis mahasiswa ITB.",
        "Olahraga", ""),
    3: ("Unit Rebana ITB",
        "Unit Rebana ITB (URI) adalah unit kegiatan mahasiswa yang bergerak di bidang seni musik rebana.",
        "Seni & Budaya", ""),
    4: ("Unit Aktivitas Tenis Meja ITB",
        "Unit Aktivitas Tenis Meja ITB (UATM ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi tenis meja mahasiswa ITB.",
        "Olahraga", ""),
    5: ("ITB Student Orchestra",
        "ITB Student Orchestra (ISO) adalah unit kegiatan mahasiswa yang mewadahi pengembangan musik orkestra bagi mahasiswa ITB.",
        "Seni & Budaya", ""),
    6: ("Persatuan Catur Mahasiswa ITB",
        "Persatuan Catur Mahasiswa ITB (PERCAMA ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi catur mahasiswa ITB.",
        "Olahraga", ""),
    7: ("Unit Kebudayaan Jepang ITB",
        "Unit Kebudayaan Jepang ITB (UKJ ITB) adalah unit kegiatan mahasiswa yang menjadi wadah pengenalan dan apresiasi budaya Jepang bagi mahasiswa ITB.",
        "Hobi & Budaya Populer", "taxonomy: unit budaya internasional; kelas alternatif bila tim menghendaki"),
    8: ("Unit Kebudayaan Aceh ITB",
        "Unit Kebudayaan Aceh ITB (UKA-ITB) adalah unit kegiatan mahasiswa yang melestarikan dan memperkenalkan budaya Aceh di lingkungan ITB.",
        "Budaya Daerah", ""),
    9: ("Korean Culture Club ITB",
        "Korean Culture Club ITB (KCC) adalah komunitas mahasiswa yang menjadi wadah apresiasi budaya Korea di ITB.",
        "Hobi & Budaya Populer", "taxonomy: unit budaya internasional; kelas alternatif bila tim menghendaki"),
    10: ("Atletik Ganesha ITB",
        "Atletik Ganesha (ATLAS) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi cabang-cabang atletik mahasiswa ITB.",
        "Olahraga", ""),
    11: ("Capoeira Brasil ITB",
        "Capoeira Brasil ITB (CBITB) adalah unit kegiatan mahasiswa yang mengembangkan seni bela diri capoeira di kalangan mahasiswa ITB.",
        "Bela Diri & Kebangsaan", ""),
    12: ("Unit Aikido ITB",
        "Unit Aikido ITB (Aikido ITB) adalah unit kegiatan mahasiswa yang mewadahi latihan dan pengembangan bela diri aikido.",
        "Bela Diri & Kebangsaan", ""),
    13: ("Keluarga Mahasiswa Islam ITB",
        "Keluarga Mahasiswa Islam ITB (GAMAIS ITB) adalah unit kegiatan mahasiswa yang menjadi wadah pembinaan dan kegiatan keislaman bagi mahasiswa ITB.",
        "Keagamaan", ""),
    14: ("Perkumpulan Seni Tari dan Karawitan Jawa ITB",
        "Perkumpulan Seni Tari dan Karawitan Jawa ITB (PSTK ITB) adalah unit kegiatan mahasiswa yang melestarikan seni tari dan karawitan Jawa di lingkungan ITB.",
        "Budaya Daerah", ""),
    15: ("Marching Band Waditra Ganesha ITB",
        "Marching Band Waditra Ganesha (MBWG) adalah unit kegiatan marching band mahasiswa ITB yang aktif dalam pertunjukan dan kompetisi.",
        "Seni & Budaya", ""),
    16: ("Unit Flag Football ITB - Ganesha Touchdown",
        "Unit Flag Football ITB - Ganesha Touchdown (UFF ITB) adalah unit kegiatan mahasiswa yang mengembangkan olahraga flag football di ITB.",
        "Olahraga", ""),
    17: ("Persekutuan Mahasiswa Kristen ITB",
        "Persekutuan Mahasiswa Kristen ITB (PMK) adalah unit kegiatan mahasiswa yang menjadi wadah persekutuan dan pembinaan iman bagi mahasiswa Kristen ITB.",
        "Keagamaan", ""),
    18: ("Koperasi Kesejahteraan Mahasiswa ITB",
        "Koperasi Kesejahteraan Mahasiswa ITB (Kokesma) adalah koperasi mahasiswa yang bergerak di bidang kewirausahaan dan pemenuhan kebutuhan mahasiswa ITB.",
        "Kewirausahaan", ""),
    19: ("8EH Radio ITB",
        "8EH Radio ITB (8EH) adalah unit kegiatan mahasiswa yang menjadi wadah pengembangan minat di bidang penyiaran radio.",
        "Media & Komunikasi", ""),
    20: ("Keluarga Mahasiswa Pencinta Alam Ganesha ITB",
        "Keluarga Mahasiswa Pencinta Alam Ganesha ITB (KMPA Ganesha ITB) adalah unit kegiatan mahasiswa yang bergerak di bidang kegiatan alam bebas dan pelestarian lingkungan.",
        "Lingkungan & Sosial", ""),
    21: ("Keluarga Mahasiswa Hindu Vidya Dharma Putra Ganesha ITB",
        "Keluarga Mahasiswa Hindu Vidya Dharma Putra Ganesha ITB (KMH ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kegiatan keagamaan Hindu di ITB.",
        "Keagamaan", ""),
    22: ("Ganesha Model United Nations Club ITB",
        "Ganesha Model United Nations Club (GMUNC) adalah unit kegiatan mahasiswa yang mengembangkan keterampilan diplomasi dan debat melalui simulasi sidang Perserikatan Bangsa-Bangsa.",
        "Penalaran & Teknologi", ""),
    23: ("Studi Teater Mahasiswa ITB",
        "Studi Teater Mahasiswa (STEMA) adalah unit kegiatan seni teater bagi mahasiswa ITB.",
        "Seni & Budaya", "needs_review: visi/misi kosong di sumber; deskripsi hanya dari nama"),
    24: ("Keluarga Paduan Angklung ITB",
        "Keluarga Paduan Angklung ITB (KPA-ITB) adalah unit kegiatan mahasiswa yang melestarikan dan mengembangkan seni musik angklung.",
        "Seni & Budaya", ""),
    25: ("U-Green ITB",
        "U-Green ITB (U-Green ITB) adalah unit kegiatan mahasiswa yang bergerak di bidang lingkungan hidup dan pembangunan berkelanjutan.",
        "Lingkungan & Sosial", ""),
    26: ("Unit Basket Ganesha ITB",
        "Unit Basket Ganesha ITB (UBG ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi bola basket mahasiswa ITB.",
        "Olahraga", ""),
    27: ("Keluarga Mahasiswa Buddhis 'Dhammañano' ITB",
        "Keluarga Mahasiswa Buddhis 'Dhammañano' ITB (KMB 'Dhammañano' ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kegiatan keagamaan Buddha di ITB.",
        "Keagamaan", ""),
    28: ("Persatuan Sepakbola ITB",
        "Persatuan Sepakbola ITB (PS ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi sepak bola mahasiswa ITB.",
        "Olahraga", ""),
    29: ("Keluarga Mahasiswa Katolik ITB",
        "Keluarga Mahasiswa Katolik ITB (KMK ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kegiatan keagamaan Katolik di ITB.",
        "Keagamaan", ""),
    30: ("Unit Budaya Lampung ITB",
        "Unit Budaya Lampung ITB (UBALA ITB) adalah unit kegiatan mahasiswa yang melestarikan dan memperkenalkan budaya Lampung di lingkungan ITB.",
        "Budaya Daerah", ""),
    31: ("Genshiken ITB",
        "Genshiken ITB adalah unit kegiatan mahasiswa yang berfokus pada budaya populer Jepang, sebagai wadah aktualisasi diri dan pengembangan kreativitas anggotanya.",
        "Hobi & Budaya Populer", ""),
    32: ("Unit Taekwondo ITB",
        "Unit Taekwondo ITB (TKD ITB) adalah unit kegiatan mahasiswa yang mewadahi latihan dan prestasi bela diri taekwondo.",
        "Bela Diri & Kebangsaan", ""),
    33: ("Unit Panahan Pasopati ITB",
        "Unit Panahan Pasopati ITB (Pasopati ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi olahraga panahan.",
        "Olahraga", ""),
    34: ("Paduan Suara Mahasiswa ITB",
        "Paduan Suara Mahasiswa ITB (PSM-ITB) adalah unit kegiatan paduan suara mahasiswa ITB yang aktif dalam kegiatan bermusik serta kompetisi dan festival paduan suara.",
        "Seni & Budaya", ""),
    35: ("Unit Robotika ITB",
        "Unit Robotika ITB (URO ITB) adalah unit kegiatan mahasiswa yang menjadi wadah pengembangan teknologi robotika dan partisipasi kontes robot.",
        "Penalaran & Teknologi", ""),
    36: ("Liga Film Mahasiswa ITB",
        "Liga Film Mahasiswa ITB (LFM ITB) adalah unit kegiatan mahasiswa yang menjadi wadah apresiasi dan produksi karya film mahasiswa.",
        "Media & Komunikasi", ""),
    37: ("ITB Dance and Performance Art Community",
        "ITB Dance and Performance Art Community (INFINITY) adalah unit kegiatan mahasiswa yang mengembangkan seni tari dan seni pertunjukan modern.",
        "Seni & Budaya", ""),
    38: ("Unit Otomotif Rakata ITB",
        "Unit Otomotif Rakata ITB (Rakata) adalah unit kegiatan mahasiswa yang bergerak di bidang rekayasa dan kompetisi otomotif.",
        "Penalaran & Teknologi", ""),
    39: ("Unit Kebudayaan Melayu Riau ITB",
        "Unit Kebudayaan Melayu Riau ITB (UKMR) adalah unit kegiatan mahasiswa yang melestarikan dan memperkenalkan budaya Melayu Riau di lingkungan ITB.",
        "Budaya Daerah", ""),
    40: ("Unit Bola Voli ITB",
        "Unit Bola Voli ITB (UBV) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi bola voli mahasiswa ITB.",
        "Olahraga", ""),
    41: ("Unit Kebudayaan Tionghoa ITB",
        "Unit Kebudayaan Tionghoa ITB (UKT) adalah unit kegiatan mahasiswa yang melestarikan dan memperkenalkan budaya Tionghoa di lingkungan ITB.",
        "Budaya Daerah", ""),
    42: ("Persaudaraan Setia Hati Terate ITB",
        "Persaudaraan Setia Hati Terate ITB (PSHT ITB) adalah unit kegiatan mahasiswa yang mengembangkan bela diri pencak silat PSHT.",
        "Bela Diri & Kebangsaan", ""),
    43: ("Unit Kesenian Minangkabau ITB",
        "Unit Kesenian Minangkabau ITB (UKM-ITB) adalah unit kegiatan mahasiswa yang melestarikan dan memperkenalkan seni dan budaya Minangkabau di lingkungan ITB.",
        "Budaya Daerah", ""),
    44: ("ITBJazz",
        "ITBJazz (ITBJazz) adalah unit kegiatan mahasiswa yang menjadi wadah pengembangan musik jazz bagi mahasiswa ITB.",
        "Seni & Budaya", ""),
    45: ("Unit Kesenian Sumatera Utara ITB",
        "Unit Kesenian Sumatera Utara ITB (UKSU) adalah unit kegiatan mahasiswa yang melestarikan dan memperkenalkan seni dan budaya Sumatera Utara di lingkungan ITB.",
        "Budaya Daerah", ""),
    46: ("Unit Softball ITB",
        "Unit Softball ITB (US ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi softball mahasiswa ITB.",
        "Olahraga", ""),
    47: ("Resimen Mahasiswa Mahawarman Batalyon I/ITB",
        "Resimen Mahasiswa Mahawarman Batalyon I/ITB (Menwa ITB) adalah unit kegiatan mahasiswa yang bergerak di bidang bela negara dan kedisiplinan.",
        "Bela Diri & Kebangsaan", ""),
    48: ("Pelita Muda ITB",
        "Pelita Muda ITB (PM) adalah unit kegiatan mahasiswa yang bergerak di bidang kepekaan sosial dan pemberdayaan masyarakat.",
        "Lingkungan & Sosial", ""),
    49: ("Unit Tenis ITB",
        "Unit Tenis ITB (UT ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi tenis lapangan mahasiswa ITB.",
        "Olahraga", ""),
    50: ("Unit Selam Nautika ITB",
        "Unit Selam Nautika ITB (Nautika ITB) adalah unit kegiatan mahasiswa yang mewadahi kegiatan dan pendidikan selam mahasiswa ITB.",
        "Olahraga", ""),
    51: ("Kelompok Studi Ekonomi dan Pasar Modal ITB",
        "Kelompok Studi Ekonomi dan Pasar Modal ITB (KSEP ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kajian ekonomi dan pasar modal.",
        "Penalaran & Teknologi", ""),
    52: ("Student English Forum ITB",
        "Student English Forum ITB (SEF ITB) adalah unit kegiatan mahasiswa yang mengembangkan kemampuan berbahasa Inggris mahasiswa ITB.",
        "Penalaran & Teknologi", ""),
    53: ("Korps Sukarela Palang Merah Indonesia Unit ITB",
        "Korps Sukarela PMI Unit ITB (KSR PMI Unit ITB) adalah unit kegiatan mahasiswa yang bergerak di bidang kepalangmerahan dan kerelawanan kemanusiaan.",
        "Kesehatan & Kerelawanan", ""),
    54: ("Techno Entrepreneur Club ITB",
        "Techno Entrepreneur Club ITB (TEC ITB) adalah unit kegiatan mahasiswa yang mengembangkan minat kewirausahaan berbasis teknologi.",
        "Kewirausahaan", ""),
    55: ("Mahasiswa Bumi Sriwijaya ITB",
        "Mahasiswa Bumi Sriwijaya ITB (MUSI ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kebersamaan dan pelestarian budaya Sumatera Selatan di ITB.",
        "Budaya Daerah", ""),
    56: ("Unit Aktivitas Bridge ITB",
        "Unit Aktivitas Bridge ITB (UAB ITB) adalah unit kegiatan mahasiswa yang mewadahi minat dan prestasi olahraga bridge.",
        "Olahraga", ""),
    57: ("Unit Kendo ITB",
        "Unit Kendo ITB (Kendo ITB) adalah unit kegiatan mahasiswa yang mengembangkan bela diri kendo di kalangan mahasiswa ITB.",
        "Bela Diri & Kebangsaan", ""),
    58: ("Aksantara ITB",
        "Aksantara ITB (Aksantara ITB) adalah unit kegiatan mahasiswa yang bergerak di bidang riset dan inovasi wahana terbang tanpa awak (UAV).",
        "Penalaran & Teknologi", ""),
    59: ("Keluarga Mahasiswa Islam ITB Kampus Cirebon",
        "Keluarga Mahasiswa Islam ITB Kampus Cirebon (KAWAI ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kegiatan keislaman bagi mahasiswa ITB Kampus Cirebon.",
        "Keagamaan", ""),
    60: ("Ganesha Interactive Media ITB",
        "Ganesha Interactive Media ITB (GIM ITB) adalah komunitas mahasiswa yang mengembangkan bakat dan keterampilan pengembangan gim serta media interaktif.",
        "Penalaran & Teknologi", ""),
    61: ("Gajah Ngomik ITB",
        "Gajah Ngomik (Gamik) adalah komunitas mahasiswa yang menjadi wadah pengembangan karya komik dan ilustrasi di ITB.",
        "Hobi & Budaya Populer", ""),
    62: ("Society of Renewable Energy ITB",
        "Society of Renewable Energy ITB (SRE ITB) adalah unit kegiatan mahasiswa yang bergerak di bidang kajian dan pengembangan energi terbarukan.",
        "Penalaran & Teknologi", ""),
    63: ("Cerberus Racing Team ITB",
        "Cerberus Racing Team ITB (CRT) adalah unit kegiatan mahasiswa yang bergerak di bidang rekayasa dan kompetisi mobil balap.",
        "Penalaran & Teknologi", ""),
    64: ("Cirebon Boardgame Community ITB",
        "Cirebon Boardgame Community ITB (CBC ITB) adalah komunitas mahasiswa yang mengembangkan minat permainan papan (board game) di ITB Kampus Cirebon.",
        "Hobi & Budaya Populer", ""),
    65: ("Gebrak Indonesia ITB",
        "Gebrak Indonesia (Gebrak) adalah unit kegiatan mahasiswa yang bergerak di bidang pergerakan sosial kemasyarakatan.",
        "Lingkungan & Sosial", ""),
    66: ("Cirebon Sport Community ITB",
        "Cirebon Sport Community ITB (CISCO) adalah komunitas olahraga mahasiswa ITB Kampus Cirebon.",
        "Olahraga", ""),
    67: ("Advance Association of Petroleum Geologists ITB",
        "Advance Association of Petroleum Geologists ITB (AAPG ITB) adalah unit kegiatan mahasiswa yang menjadi wadah kajian geologi perminyakan.",
        "Penalaran & Teknologi", ""),
    68: ("Ganesha Pintar ITB",
        "Ganesha Pintar (Forum Mahasiswa KIP-K ITB) adalah wadah kebersamaan dan pengembangan diri bagi mahasiswa penerima KIP Kuliah di ITB.",
        "Lingkungan & Sosial", "verify: klasifikasi kesejahteraan/kemahasiswaan"),
    69: ("Fit Levitating ITB",
        "Fit Levitating ITB adalah komunitas kebugaran yang mendorong gaya hidup sehat bagi mahasiswa ITB.",
        "Olahraga", "verify: nama informal; pastikan status resmi unit"),
}

EXCLUDED = {
    ("himpunan", 3): "Kamil Pascasarjana ITB - organisasi keagamaan pascasarjana; di luar cakupan lembaga Anmategra (konfirmasi tim)",
    ("himpunan", 45): "IMDI - duplikat dari Himpunan #32 (baris tanpa konten); dedupe by name",
}

HEADER = ["email", "name", "description", "founding_date", "ending_date",
          "type", "major", "field", "member_count"]


def main():
    data = json.load(open(RAW, encoding="utf-8"))
    rows, flags, km_count = [], [], 0
    counts = {"Himpunan": 0, "UKM": 0}

    for item in data["lembaga"]:
        tab = item["tab"]
        no = int(item["no"])
        if tab == "km":
            km_count += 1
            continue
        key = (tab, no)
        if key in EXCLUDED:
            flags.append(f"EXCLUDED {tab} #{no}: {EXCLUDED[key]}")
            continue
        source = HIMPUNAN.get(no) if tab == "himpunan" else UKM.get(no)
        if source is None:
            flags.append(f"UNMAPPED {tab} #{no}: {item['nama']} - no enrichment entry")
            continue
        name, desc, attr, flag = source
        if flag:
            flags.append(f"{tab} #{no} ({name}): {flag}")
        tipe = "Himpunan" if tab == "himpunan" else "UKM"
        counts[tipe] += 1
        rows.append({
            "email": "",
            "name": name,
            "description": desc,
            "founding_date": "",
            "ending_date": "",
            "type": tipe,
            "major": attr if tab == "himpunan" else "",
            "field": attr if tab == "ukm" else "",
            "member_count": "",
        })

    unmapped = [f for f in flags if f.startswith("UNMAPPED")]
    if unmapped:
        print("ERROR: unmapped rows exist — fix enrichment tables first:", file=sys.stderr)
        for f in unmapped:
            print("  " + f, file=sys.stderr)
        return 1

    with open(OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADER, lineterminator="\n")
        w.writeheader()
        w.writerows(rows)

    print(f"Wrote {OUT}")
    print(f"  Himpunan: {counts['Himpunan']}  UKM: {counts['UKM']}  total: {len(rows)}")
    print(f"  excluded: {len(EXCLUDED)}  KM tab skipped: {km_count}")
    print(f"\nQA flags ({len(flags)}):")
    for f in flags:
        print("  - " + f)
    return 0


if __name__ == "__main__":
    sys.exit(main())
